select
  *
from Task
;

CREATE TABLE Task (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  queue_names text[] NOT NULL,
  type varchar(255) NOT NULL,
  status varchar(50) NOT NULL,
  payload json NULL,
  result json NULL,
  program_path text NULL,
  program_type varchar(255) NULL,
  created_at timestamp NOT NULL,
  executed_at timestamp NULL,
  time_elapsed interval NULL
);

INSERT INTO Task (queue_names, type, status, payload, result, program_path, program_type, created_at, executed_at, time_elapsed)
VALUES
(
  ARRAY['main', 'external'],
  'sync-with-partner2',
  'COMPLETED',
  '{ \"customer\": \"Alex Cross\", \"items\": {\"product\": \"Tea\",\"qty\": 6}}',
  null,
  null,
  null,
  NOW(),
  NOW() - INTERVAL '1 day',
  INTERVAL '1 day 2 hours'
),
(
  ARRAY['main', 'internal'],
  'sync-with-partner1',
  'QUEUED',
  '{ \"customer\": \"Alex Cross\", \"items\": {\"product\": \"Tea\",\"qty\": 6}}',
  null,
  '/Users/manyu/projects/tooling_notes/fs_prac',
  'dotnet-cli',
  NOW(),
  null,
  null
)
;
